### ISSUE TITLE
What package did you use to get the visualization in paper?

### ISSUE THREAD

**Issue by alexzhou907** [RuojinCai/ShapeGF#1]
The scripts seem to use matplotlib which doesn't give you shading and lighting. For the figures in the paper what package did you use to render them?

**Comment by RuojinCai** [comment]
We use [Mitsuba Renderer](http://www.mitsuba-renderer.org/). Please refer to the following github repository for our point cloud rendering code: https://github.com/zekunhao1995/PointFlowRenderer.
